version: '3.4'

services:
  blazorapp1.server:
    image: ${DOCKER_REGISTRY-}blazorapp1server
    build:
      context: .
      dockerfile: src/BlazorApp1/Server/Dockerfile
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data