# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "Horusec Scan"

on:
   push:
     branches: [ "none" ]
   pull_request:
     # The branches below must be a subset of the branches above
     branches: [ "none" ]
#   schedule:
#     - cron: '22 20 * * 6'

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Horusec
        env:
          AUTHOR: rahul.soni@knoldus.com
          HORUSEC_CLI_RETURN_ERROR_IF_FOUND_VULNERABILITY: "true"
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -p ./ --config-file-path=horusec-config.json -O report.txt --return-error=true
